model_name: nnformer
id: optimised
debug: False
save_to_original_spacing: True

data_dir: /path/to/the/data/
checkpoint: null
epochs: 2500
batch_size: 2
loss: DiceCELoss

do_ds: True
include_background: False
dice_prop: 0.5
optimizer: sgd
lrschedule: null
optim_lr: 0.01
reg_weight: 0.00003
poly_learning_rate: True

#Specific nnformer
crop: randByClass
num_samples: 500

net_numpool: 5
nn_former_embed_dim: 96
depths: [ 2, 2, 2, 2 ]
nn_former_num_heads: [ 3, 6, 12, 24 ]
patch_size: [ 4, 4, 1 ]
window_size: [ [ 5, 5, 3 ], [ 5, 5, 3 ], [ 10, 10, 7 ], [ 5, 5, 3 ] ]
down_stride: [ [ 4, 4, 1 ], [ 8, 8, 1 ], [ 16, 16, 2 ], [ 32, 32, 4 ] ]
deep_supervision_scales: [ [ 2, 2, 1 ], [ 4, 4, 2 ], [ 8, 8, 4 ], [ 16, 16, 8 ], [ 32, 32, 8 ] ]
ds_retained_len: 3

#Data Augmentation
roi_x: 224
roi_y: 224
roi_z: 64

image_fidelity_aug: True
luminance_and_contrat_aug: True
scaling_and_resolution_aug: True


