model_name: nnunet
id: optimised
debug: False
save_to_original_spacing: True

data_dir: /path/to/the/data/
checkpoint: null
epochs: 1700
batch_size: 2
loss: DiceCELoss
do_ds: True
optimizer: adam
lrschedule: null
optim_lr: 0.0001
reg_weight: 0.00003
poly_learning_rate: True

#Specific nnunet
num_samples: 500

net_numpool: 5
deep_supervision_scales: [ [ 2, 2, 1 ], [ 4, 4, 2 ], [ 8, 8, 4 ], [ 16, 16, 8 ], [ 32, 32, 8 ] ]
ds_retained_len: 5

#Data Augmentation
roi_x: 384
roi_y: 288
roi_z: 64

image_fidelity_aug: False
luminance_and_contrat_aug: True
scaling_and_resolution_aug: False
