model_name: unetr
id: optimised
debug: False
save_to_original_spacing: True

data_dir: /path/to/the/data/
checkpoint: null
epochs: 3000
batch_size: 2
loss: Dice
optimizer: adam
optim_lr: 0.0001
reg_weight: 0.00003
val_every: 1
warmup_epochs: 50
smooth_dr: 1e-6
smooth_nr: 0.0

#Specific UNeTr
pos_embed: perceptron
norm_name: instance
num_heads: 12
mlp_dim: 3072
hidden_size: 768
feature_size: 16


#Data Augmentation
roi_x: 192
roi_y: 160
roi_z: 64

image_fidelity_aug: False
luminance_and_contrat_aug: True
scaling_and_resolution_aug: True
